apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "permission-access"
spec:
  kprobes:
    ####################################################################
    # sys_chmod
    ####################################################################

    ####################################################################
    # Create Or Modify System Process T1543
    - call: "sys_chmod"
      syscall: true
      args:
        - index: 0
          type: "string"
        - index: 1
          type: "int"
      selectors:
        - matchArgs:
          - index: 0
            operator: "Postfix"
            values: [".service"]
          - index: 1
            operator: "Equal"
            values: ["755", "777"] 
          matchPIDs:
            - operator: "NotIn"
              followForks: true
              isNamespacePID: true
              values: [0]
    ####################################################################

    ####################################################################
    # sys_capget
    ####################################################################

    ####################################################################
    # Privilege Escalation T1068
    - call: "sys_capget"
      syscall: true
      selectors: [{matchActions: [{action: Post}]}]
    ####################################################################

    ####################################################################
    # sys_capset
    ####################################################################

    ####################################################################
    # Privilege Escalation T1068
    - call: "sys_capset"
      syscall: true
      selectors: [{matchActions: [{action: Post}]}]
    ####################################################################

    ####################################################################
    # sys_setresuid
    ####################################################################

    ####################################################################
    # Privilege Escalation T1068
    - call: "sys_setresuid"
      syscall: true
      selectors: [{matchActions: [{action: Post}]}]
    ####################################################################